title: [Praktikum Struktur Data Genap 2023/2024]
description: [Prodi S1 Teknik Informatika - Universitas Negeri Surabaya]
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme